// WARNING: Do not edit this file. Copy or rename it as config.js before change it

// To see debug messages into the browser console set this parameter as true
const DEBUG = false;

// Default veil timeout (milliseconds)
const VEIL_TIMEOUT = 1000;

// Connection parameters
const PROTOCOL = 'https'; // http or https
const HOST = 'fhcomplete.org'; // host name
const PROJECT = 'ClientTemplate'; // project name
const PATH = 'controller'; // path to the router
const ROUTER = 'router.php'; // router name
