<?php

// WARNING: Do not edit this file. Copy or rename it as config.php before change it

$debug = false; // if it set as true debug infos will be logged in the apache error log

$activeConnection = 'DEFAULT'; // the used configuration set of the chosen connection

// Example of a configuration set, all parameters are required!
$connection = array(
	'DEFAULT' => array(
		USERNAME => 'fhcomplete', //
		PASSWORD => '****', //
		API_KEY_NAME => 'FHC-API-KEY', //
		API_KEY_VALUE => 'testapikey@fhcomplete.org', //
		PROTOCOL => 'https', //
	    HOST => 'fhcomplete.org', //
	    PATH => 'fhcomplete', //
	    ROUTER => 'index.ci.php', //
	    WS_PATH => 'api/v1' //
	)
);

$cacheEnabled = true; // to debug change it to false, it will always overwrite the cache

// Example of route configuration
// Every element of the first level is the alias of the remote web service
// Every first element must contain a string with the <path/name/method to call> of the remote web service (REQUIRED)
// OR an array having:
//	- as element REMOTE_WS the <path/name/method to call> of the remote web service (REQUIRED)
//	- as element HOOK the hook to manipulate the response from the remote web service (OPTIONAL)
//	- as element AUTH a boolean: if true (default) to perform this call the user must be logged in (OPTIONAL)
//
// To use login capabilities must be present the element LOCAL_LOGIN_CALL in the first level
$route = array(
	LOCAL_LOGIN_CALL => array( // required if access functionalities are needed
		REMOTE_WS => 'CheckUserAuth/CheckUserAuth', // remote web service name (REQUIRED)
		HOOK => 'hookLogin' // hook to call after the remote web service call (OPTIONAL)
	),
	LOCAL_LOGOUT_CALL => LOCAL_LOGOUT_CALL, // this call will never performed, therfore you can place here what you want
	'loadPhrases' => array(
		REMOTE_WS => 'system/Phrase/Phrases',
		CACHE_PARAMETER => CACHE_ENABLED // cache always enabled, the web interface cannot change this behaviour
	),
    'testHookNoLogin'  => array(
        REMOTE_WS => 'Test/Test', // remote web service name (REQUIRED)
        HOOK => 'hookTest', // hook to call after the remote web service call (OPTIONAL)
		AUTH => false	// by default is true (OPTIONAL)
    ),
	'testNoHook'  => 'Test/Test', // remote web service name (REQUIRED)
	'loadPersonData' => array(
		REMOTE_WS => 'person/Person/Person',
		SESSION_PARAMS => array('person_id')
	),
	'savePersonData' => array(
		REMOTE_WS => 'person/Person/Person',
		SESSION_PARAMS => array('person_id')
	)
);
